name: npm publish

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, run linter and tests
      run: |
        npm ci
        npm run build
        npm run lint
        npm run ts-check
        npm t
      env:
        CI: true

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
